### ISSUE TITLE
Make related JavaScript libraries as package.json dependencies

### ISSUE THREAD

**Issue by PiiXiieeS** [Sanofi-IADC/konviw#284]
**Is your feature request related to a problem? Please describe.**
This enhancements is to improve the maintainability of the source code and make easier the upgrade of javascript libray dependencies which currently are manually copied in a folder.

**Describe the solution you'd like**
Install the related libraries via package manager and include a webpack or other builder script to generate the javascript libraries during DEV and BUILD phase.

**Describe alternatives you've considered**
We could continue as today, because those libraries are not evolving very frequently but we may face some regressions in the long term.

**Additional context**
Libraries that we shall move to dependencies are:
- [gridjs](https://github.com/grid-js/gridjs)
- [highlight](https://github.com/highlightjs/highlight.js)
- [iframeResizer](https://github.com/davidjbradshaw/iframe-resizer)
- [reveal](https://github.com/hakimel/reveal.js/)
- [zooming](https://github.com/kingdido999/zooming)

**Comment by MeStrak** [comment]
Good suggestion, I think it's particularly important to ensure that we upgrade if vulnerabilities are detected in those libraries which we wouldn't be updated automatically about otherwise.

There's also something else to consider in #282 where .js and .css dependencies become a bit more complex as we can't directly inject them into the html page in the same way that we do with the iFrame model. so if we go with that new feature we'll need to work on a way to ensure all dependencies are correctly aligned.

**Comment by PiiXiieeS** [comment]
Hi @MeStrak and @kiru42 
Coming back on this idea I have thought 2 possible strategies:

### Option 1 - to use webpack or JS bundler to bundle those libraries in the dist folder.
It may be something like this:
```ts
import { resolve } from 'path';

export default {
  mode: 'development',
  entry: {
    gridjs: './node_modules/ ... /gridjs/ ... .js',
    zooming: './node_modules/zooming/ ... .js',
  },
  output: {
    filename: '[name].bundle.js',
    path: resolve(__dirname, 'dist'),
  },
};
```
Then running `npx webpack` will generate separate bundles for each of our libraries.
The main constraint of this approach is to have to deal with the bundling of each of the libraries which will come with their own constraints and challenges. So in the prototype I tested, I took directly the minified version already included in the `npm install` in the node_modules folder, so basically a simple copy to the `dist` folder shall work.
In this copy process we can handle `js` and `css` separately in order to cope properly with the two distinct flavours of konviw: styled pages or [headless pages](https://www.storyblok.com/tp/headless-cms-explained).

### Option 2 - to go back to `js` and `css` delivered by your favourite CDN
The clearly advantages of this approach are:
- We do not have to bother ourselves of the bundling process and can consume directly the minified version of both `js` and `css`.
- It takes already advantage of the worldwide distribution of the CDN. For instance cdnsjs by Cloudflare.
Example for GridJS would be something like:

```html
// ----------- GridJS -----------
// from https://github.com/explore

// stylesheets
<link rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/gridjs/5.0.2/theme/mermaid.min.css" 
  integrity="sha512-QT3siPsD/eTF0b7f9Vq2eHf456XGoqXaiwmqpuIoYwRKnLgpnyntOlebCf/6WtXoXRZV7LupbEdvbgV2Lh0zmA==" 
  crossorigin="anonymous" 
  referrerpolicy="no-referrer" />

// javascript
<script src="https://cdnjs.cloudflare.com/ajax/libs/gridjs/5.0.2/gridjs.umd.min.js" 
  integrity="sha512-rubYQN7/owwJAEjUqavApiWZzpg7OpCDpqYkG6R1x+Xh6qXzAR5Q5FNbr+OzrYY4MC06Lh2OqSrAB9M1JuaTqQ==" 
  crossorigin="anonymous" 
  referrerpolicy="no-referrer">
</script>
```

Last but not least as some libraries used are only intended to be used for the styled pages we could gather the addition of both `js` and `css` in a dedicated step so it can be called only where it makes sense.
This would be:
- render page
  - gridjs
  - highlight
  - iframeResizer
  - zooming
- render slides
  - reveal

So the headless konviw api could use the `js` and `css` components in the frontend side, if it is wished, or just rely on the headless processing of the content by cheerio.

**Comment by MeStrak** [comment]
@PiiXiieeS CDN works for me. As I said in my first comment the best thing about this overall change is to avoid security vulnerabilities thanks to auto updated libraries. I checked and Renovate does support this type of dependency reference: https://www.whitesourcesoftware.com/free-developer-tools/blog/automatically-update-cdnjs-dependencies/.

**Comment by kiru42** [comment]
@PiiXiieeS I think the Option 2 is really nice since that could improve the loading performance of these assets on client side.
On  the other hand, we should check if renovate will still handle dynamically injected assets since we are not going to use plain html.
