### ISSUE TITLE
Add Cypress E2E testing

### ISSUE THREAD

**Issue by MeStrak** [Sanofi-IADC/konviw#298]
**Is your feature request related to a problem? Please describe.**
Before Konviw was released as open source we had some Cypress tests running internally (requested by @PiiXiieeS) to ensure pages were rendered correctly by doing visual checks.

There have been several fairly significant updates to the app recently, thankfully with no regressions. As we continue to improve and add more functionality it would be great to get these tests back up and running on the open source version.
- More confidence that we're not breaking existing functionality when making a change, eventually resulting in a faster deployment cycle
- Faster merging of Renovate changes thanks to increased confidence that the rendered page is tested

**Describe the solution you'd like**
- Copy the content from the previously used Confluence pages content to the official Konviw Confluence
- Run the Cypress tests through GitHub actions (either in a new action, or a step in the existing CI action) - decide during implementation whether these tests are on a test deployment version on Vercel
- Run the Cypress tests on a deployed internal version

**Describe alternatives you've considered**
- Remove Cypress tests and use Jest E2E tests: we should add some additional Jest testing, but this should not replace tests of the rendered pages using Cypress
- Simplify the Cypress tests instead of just copying them: we probably should simplify some of the tests, but let's do the migration first to get the tests running before we do that (see additional context of this issue)
- Run Cypress tests internally only: against the open source spirit of Konviw, and also makes the CICD workflow more complex. The only benefit would be the initial time saved as we wouldn't need to recreate the test content in the Konviw Confluence space.

**Additional context**
I believe that the previous Cypress tests were full page visual checks. They work well but this strategy can be a bit aggressive and result in a lot of test maintenance. After this implementation we can review to see whether some of the tests can be simplified for easier maintenance.

**Comment by kiru42** [comment]
Hi @MeStrak @PiiXiieeS 

I did the following steps:

- [X]  Copy the content from the previously used Confluence pages content to the official Konviw Confluence (most of the pages were already copied by @PiiXiieeS, I just had to divide some pages to match the cypress tests)
- [X] Migrated and updated all the tests to match konviw's confluence urls
- [X] Run the Cypress tests through GitHub actions (I did it in a new workflow **Cypress Tests**)
- [X] decide during implementation whether these tests are on a test deployment version on Vercel (Currently the tests are done on https://konviw.vercel.app)
- [ ] We probably need to deploy each Pull Request version to vercel and run the cypress test against that version

I was not able to do this one:

- [ ] Run the Cypress tests on a deployed internal version (I was not able to do that, Internal version's pages have different paths on confluence, it will be tricky to manage that, or we have to add separate tests to match these urls and probably have to manage them in another repository)

**Comment by MeStrak** [comment]
Re-opening pending implementation of deployed version for testing (test on the current version being pushed instead of previous version).

**Comment by kiru42** [comment]
We are now testing preview URL's from vercel for each PR. I am closing this issue.
